dist: xenial

language: java
  
os:
  - linux

addons:
  apt:
    packages:
      - openjdk-8-jdk-headless

jdk:
  - openjdk8 # used by maven runtime

cache:
  directories:
  - $HOME/.m2/bin
  - $HOME/.m2/repository
before_cache:
  - rm -rf $HOME/.m2/repository/net/sf/oval

install:
  - which java
  - echo JAVA_HOME=$JAVA_HOME
  - ls -l /usr/lib/jvm/

before_script:
  - unset _JAVA_OPTIONS # https://github.com/travis-ci/travis-ci/issues/8408

script:
  - bash .travis/build.sh