dist: bionic

language: java
  
os:
  - linux

git:
  depth: 2

jobs:
  include:
    - os: linux
      jdk: openjdk8 # used by Maven runtime
      env: 
        - MAY_CREATE_RELEASE=true
        - JAVA_VERSION=8
    - os: linux
      jdk: openjdk11 # used by Maven runtime
      env:
        - MAY_CREATE_RELEASE=false
        - JAVA_VERSION=11
  allow_failures:
    - jdk: openjdk11 # used by Maven runtime

cache:
  directories:
  - $HOME/.m2/bin
  - $HOME/.m2/repository
  - $HOME/.xshare
before_cache:
  - rm -rf $HOME/.m2/repository/net/sf/oval

install:
  - printenv | sort
  - which java
  - echo JAVA_HOME=$JAVA_HOME
  - ls -l /usr/lib/jvm/
  - ls -l /usr/local/lib/jvm/
  - ls -l $HOME/.m2

before_script:
  - unset _JAVA_OPTIONS # https://github.com/travis-ci/travis-ci/issues/8408

script:
  - bash .ci/build.sh